//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongsRazor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class top_albums
    {
        public int position { get; set; }
        public string artist { get; set; }
        public string album { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<decimal> raw_total { get; set; }
        public Nullable<decimal> raw_usa { get; set; }
        public Nullable<decimal> raw_uk { get; set; }
        public Nullable<decimal> raw_eur { get; set; }
        public Nullable<decimal> raw_row { get; set; }
    }
}
